// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxfsvitnhycqueuxcviz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4ZnN2aXRuaHljcXVldXhjdml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTQ1MjEsImV4cCI6MjA2MzIzMDUyMX0.JUNbZSs9UjxKudxiA6aRJQCEf0GE3HBOUVjCtmEIytA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);